### ISSUE TITLE
Upgrade to 1.96b please

### ISSUE THREAD

**Issue by vanhauser-thc** [arizvisa/afl-cygwin#1]
It would be great if you would invest your time to upgrade to AFL 1.96b
Thank you!

**Comment by arizvisa** [comment]
Thanks for showing interest! Once I'm done with some of the other non-related stuff I'm currently working on, I'll revisit this. I already have a patch for 1.96b per your request but need to streamline some of the building and expose the LdrpInitializeProcess hack to the builder so they can switch between the native-forking and cygwin's fork. I'll update this particular issue when it happens.

Thanks!

**Comment by vanhauser-thc** [comment]
great to hear its not a dead repository :)

**Comment by arizvisa** [comment]
fixed by commit 641373773d0d05207b28b9e9b2e061953c0e85e8.

**Comment by vanhauser-thc** [comment]
thanks!
