### ISSUE TITLE
Still fails to compile :)

### ISSUE THREAD

**Issue by vanhauser-thc** [arizvisa/afl-cygwin#8]
I am at the airport atm, waiting for boarding, so I can not have a detailed look, but it seems to be jst a small typo

cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"1.96b\" afl-as.c -o afl-as
In file included from afl-as.c:38:0:
afl-as.h:117:40: error: expected ',' or ';' before 'STR'
     #define CALL(str)       NATIVECALL(STR)
                                        ^
afl-as.h:116:37: note: in definition of macro 'NATIVECALL'
     #define NATIVECALL(str) "call " str "\n"
                                     ^
afl-as.h:232:3: note: in expansion of macro 'CALL'
   CALL("getenv")
   ^
Makefile:71: recipe for target 'afl-as' failed

**Comment by arizvisa** [comment]
Hoh, what? Commit cc0868a542098275cc09b61c6073ce19863b45c3 seems to build for me...

Are you building with $ make WIN32=1?

[build.20160312.txt](https://github.com/arizvisa/afl-cygwin/files/170750/build.20160312.txt)

**Comment by arizvisa** [comment]
Ah yeah, you're not doing WIN32=1...sorry bout that. I really need to write documentation for this..you know how that goes. ;-)

**Comment by arizvisa** [comment]
Although, I specifically made that a define with the intention that old afl should still work with the same build environment so this is still a bug.

So yeah, my bad at wasting your time trying to get this thing built.

**Comment by arizvisa** [comment]
kk. fixed the type-o you pointed out. try building with `$ make WIN32=1 all` though :-)

**Comment by arizvisa** [comment]
Fixed by commit 9a3040ce0471169f338b60dfc616c59ec1b2334b.

**Comment by vanhauser-thc** [comment]
I did not see the WIN32=1 requirement, but then again I was at the airport, quickly trying to update and compile before boarding :)

it ompiles now, thanks!

There are few warnings that however are not important:

afl-gcc.c: In function 'main':
afl-gcc.c:318:5: warning: implicit declaration of function 'scream_parameters' [-Wimplicit-function-declaration]
     scream_parameters(cc_params);
     ^
afl-gcc.c: At top level:
afl-gcc.c:327:1: warning: conflicting types for 'scream_parameters'
 scream_parameters(char*\* parms)
 ^
afl-gcc.c:318:5: note: previous implicit declaration of 'scream_parameters' was here
     scream_parameters(cc_params);
     ^
winapi.c: In function '_fork_child_entry':
winapi.c:354:5: warning: implicit declaration of function 'dll_dllcrt0' [-Wimplicit-function-declaration]
     dll_dllcrt0();
     ^
winapi.c: In function 'native_dup':
winapi.c:555:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_from_descriptor((int)oldd, &fd) == -1)
                          ^
In file included from winapi.c:12:0:
winapi.c:561:13: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     assert(((int)(res) & 3) != (int)res); // ensure that returned handle is not a magic value (should be aligned to 4 anyways)
             ^
winapi.c:561:32: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     assert(((int)(res) & 3) != (int)res); // ensure that returned handle is not a magic value (should be aligned to 4 anyways)
                                ^
winapi.c: In function 'native_dup2':
winapi.c:571:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_from_descriptor((int)newd, &hTarget) == 0)
                          ^
winapi.c:574:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_to_descriptor(res, (int)newd) == -1)
winapi.c: In function 'native_read':
winapi.c:617:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_from_descriptor((int)fd, &_fd) == -1)
                          ^
winapi.c: In function 'native_write':
winapi.c:633:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_from_descriptor((int)fd, &_fd) == -1)
                          ^
winapi.c: In function 'native_close':
winapi.c:647:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (_from_descriptor((int)fd, &_fd) == -1)
                          ^
afl-fuzz.c: In function 'check_binary':
afl-fuzz.c:6595:64: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
   if (f_hdr[0] != 'P' || f_hdr[1] != 'E' || f_hdr[2] != '\x00' && f_hdr[3] != '\x00')
afl-fuzz.c:6611:7: warning: implicit declaration of function 'memmem' [-Wimplicit-function-declaration]
       !memmem(f_data, f_len, SHM_ENV_VAR, strlen(SHM_ENV_VAR) + 1)) {
       ^
